In [62]:
import pandas as pd

Предварительно данные были разбиты на 26 отдельных датасетов, каждый из которых был сохранен в отдельном csv файле на google disk:

In [63]:
from google.colab import drive
drive.mount('/content/drive')
!ls "/content/drive/My Drive/FlowPS/data"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
GSE18728.csv  GSE25066.csv  GSE50948.csv  GSE9782.csv		  TCGA_LGG.csv
GSE20181.csv  GSE32646.csv  GSE5122.csv   TARGET10.csv		  TCGA_UC.csv
GSE20194.csv  GSE37946.csv  GSE55145.csv  TARGET20Busulfan.csv
GSE20271.csv  GSE39754.csv  GSE59515.csv  TARGET20NoBusulfan.csv
GSE22358.csv  GSE41998.csv  GSE68871.csv  TARGET50.csv
GSE23988.csv  GSE42822.csv  GSE76360.csv  TCGA_LC.csv

Создадим список из 23 датасетов, которые нужно преобразовать(GSE22358, GSE76360 и TCGA-UC не учитываем, так как в них количества ответчиков и неответчиков несбалансированы):

In [36]:
data = ['GSE18728.csv',  'GSE25066.csv',  'GSE50948.csv',  'GSE9782.csv',	'TCGA_LGG.csv',
        'GSE20181.csv',  'GSE32646.csv',  'GSE5122.csv',   'TARGET10.csv', 'GSE20194.csv',
        'GSE37946.csv',  'GSE55145.csv',  'TARGET20Busulfan.csv','GSE20271.csv', 
        'GSE39754.csv',  'GSE59515.csv',  'TARGET20NoBusulfan.csv',
        'GSE41998.csv',  'GSE68871.csv',  'TARGET50.csv',
        'GSE23988.csv',  'GSE42822.csv',  'TCGA_LC.csv']

Преобразовываем все датасеты к нужному виду:

In [ ]:
for i in data:
  df = pd.read_csv('/content/drive/My Drive/FlowPS/data/' + i)
  df2 = df.T
  df2 = df2.reset_index(drop=True)

  new_header = df2.iloc[0] 
  df2 = df2[1:] 
  df2.columns = new_header 
  df2 = df2.drop(df2.columns[[0]], axis='columns')

  df2['Sample ID'] = df2.index
  cols = df2.columns.tolist()
  cols = cols[-1:] + cols[:-1]
  df2 = df2[cols]

  df2.to_csv('/content/drive/My Drive/FlowPS/change_data/' +  i, index=False)

Посмотрим на преобразованный датасет на примере GSE18728:

In [61]:
df = pd.read_csv('/content/drive/My Drive/FlowPS/change_data/GSE18728.csv')
df.head()

   Sample ID  Binary response       A1BG  ...         ZYX       ZZEF1        ZZZ3
0          1                0  49.999995  ...  276.170368  151.806116  591.821194
1          2                0  49.999995  ...  190.563866   97.582430  555.481207
2          3              100  49.999995  ...  281.911714  107.253264  371.015336
3          4                0  49.999995  ...  119.531889   94.494260  644.816684
4          5              100  57.411779  ...  155.780068  111.708393  648.125073

[5 rows x 20735 columns]